---
title: "Project_2"
author: "Fabio_Savorgnan"
date: "3/14/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message = F)
```


```{r }
library(dplyr)
library(ggplot2)
library(tidyr)
library(SDMTools)
library(readr)
library(digest)
library(ISLR)
library(car) 
library(leaps)
library( Matrix)
library(foreach)
library(glmnet)
library(gridExtra)
library(lsmeans)
library(limma)
library(Sleuth3)
library(tseries)
library(forecast)
library(ggplot2)
library(MASS)
library(mvtnorm)
library(epitools)
library(samplesizeCMH)
library(caret)
```

# Loading the data
```{r }
bank_20 = read.csv("bank-additional-full.csv", sep=";")
head(bank_20)
bankadit<- read.csv("bank-additional.csv", sep=";")
bank_17<-read.csv2("bank-full.csv", sep=";")
bank<-read.csv2("bank.csv", sep=";")
```


```{r }
summary(bank_20)
```


# Does not look like any NAs in either data set
```{r }
#Does not look like any NAs in either data set
sapply(bank_20, function(x) sum(is.na(x)))
sapply(bank_17, function(x) sum(is.na(x)))
```

#pdays- about 40k of the 41k are at level 999, no previous contact 
#could bin this data 
```{r }
hist(bank_20$pdays)
temp = bank_20 %>% filter(pdays != 999)
dim(temp)
hist(temp$pdays)
```

# Reshape for a balance data
```{r }
yes_answer = bank_20 %>% filter(y == "yes")

no_answer_all = bank_20 %>% filter(y == "no")
no_indices = sample(dim(no_answer_all)[1], dim(yes_answer)[1])
no_answer = no_answer_all[no_indices,]

balanced_bank_20 = rbind(yes_answer, no_answer)

balanced_indices = sample(dim(balanced_bank_20)[1], round(dim(balanced_bank_20)[1] * .1 ))
balanced_test = balanced_bank_20[balanced_indices,]
balanced_test
balanced_train = balanced_bank_20[-balanced_indices,]
balanced_train

```

# Plot EDA in general
```{r }
plot(as.factor(bank_20$y), bank_20$age,xlab="Loan",ylab="Age",title="Credict Assessment")
plot(y~job,data=bank_20, main="Credict Assessment",
   xlab="Job", ylab="Loan")
plot(y~marital,data=bank_20, main="Credict Assessment",
   xlab="Matital", ylab="Loan")
plot(y~education,data=bank_20, main="Credict Assessment",
   xlab="Education", ylab="Loan")
plot(y~ default,data=bank_20, main="Credict Assessment",
   xlab="Default", ylab="Loan")
plot(y~housing,data=bank_20, main="Credict Assessment",
   xlab="Housing", ylab="Loan")
plot(y~loan,data=bank_20, main="Credict Assessment",
   xlab="Loan_Y_N_before", ylab="Loan")
plot(y~contact,data=bank_20, main="Credict Assessment",
   xlab="Contact", ylab="Loan")
plot(y~month,data=bank_20, main="Credict Assessment",
   xlab="Month", ylab="Loan")
plot(y~day_of_week,data=bank_20, main="Credict Assessment",
   xlab="Day_of_week", ylab="Loan")
plot(y~poutcome,data=bank_20, main="Credict Assessment",
   xlab="Poutcome", ylab="Loan")
plot(duration~y  ,data=bank_20, main="Credict Assessment",
   xlab="Duration ", ylab="Loan", col=c(0,5000))
plot(campaign~y  ,data=bank_20, main="Credict Assessment",
   xlab="Campaign", ylab="Loan",col=c(1,56))
plot(previous~y  ,data=bank_20, main="Credict Assessment",
   xlab="Previous", ylab="Loan",col=c(1,56))
plot(y~emp.var.rate  ,data=bank_20, main="Credict Assessment",
   xlab="Emp.var.rate", ylab="Loan")
plot(y~cons.price.idx,data=bank_20, main="Credict Assessment",
   xlab="Cons.price.idx", ylab="Loan")
plot(y~cons.conf.idx,data=bank_20, main="Credict Assessment",
   xlab="cons.conf.idx ", ylab="Loan")
plot(euribor3m~y,data=bank_20, main="Credict Assessment",
   xlab="Loan", ylab="euribor3m")
plot(y~nr.employed,data=bank_20, main="Credict Assessment",
   xlab="nr.employed", ylab="Loan")
#bank_20 %>% ggplot(aes(x = age, y = cons.price.idx, color = y)) + geom_point()
#bank_20 %>% ggplot(aes(y = job, fill = job) + geom_boxplot())
#bank_20 %>% ggplot(aes(y = duration, fill = y)) + geom_boxplot()
```
# EDA for categorical values with proportion table

```{r }
attach(bank_20)
ftable(addmargins(table(y,job))) 
job=factor(job)


ftable(addmargins(table(y, marital)))
marital=factor(marital)


ftable(addmargins(table(y,education)))
education=factor(education)


ftable(addmargins(table(y,default)))
education=factor(default)


ftable(addmargins(table(y,housing))) 
job=factor(housing)


ftable(addmargins(table(y, loan)))
marital=factor(loan)


ftable(addmargins(table(y,contact)))
education=factor(contact)


ftable(addmargins(table(y,month)))
education=factor(month)


ftable(addmargins(table(y,day_of_week)))
education=factor(day_of_week)


ftable(addmargins(table(y,poutcome)))
education=factor(poutcome)

#to get proportions that make sense
prop.table(table(y,job),2)
prop.table(table(y,education),2)
prop.table(table(y,default),2)
prop.table(table(y,housing),2)
prop.table(table(y,loan),2)
prop.table(table(y,contact),2)
prop.table(table(y,month),2)
prop.table(table(y,day_of_week),2)
prop.table(table(y,poutcome),2)

#Visualize
plot(y~job,col=c("red","blue"))
plot(y~education,col=c("red","blue"))
plot(y~default,col=c("red","blue"))
plot(y~marital,col=c("red","blue"))
plot(y~housing,col=c("red","blue"))
plot(y~loan,col=c("red","blue"))
plot(y~contact,col=c("red","blue"))
plot(y~month,col=c("red","blue"))
plot(y~day_of_week,col=c("red","blue"))
plot(y~poutcome,col=c("red","blue"))
```


```{r }

```



#PCA for continuous variables
```{r }
pc.bc<-prcomp(bank_20[,-c(2,3,4,5,6,7,8,9,10,15,21)],scale.=TRUE)
pc.bc.scores<-pc.bc$x
#Adding the response column to the PC's data frame
pc.bc.scores<-data.frame(pc.bc.scores)
pc.bc.scores$loan<-bank_20$y

#Use ggplot2 to plot the first few pc's
library(ggplot2)
ggplot(data = pc.bc.scores, aes(x = PC1, y = PC2)) +
  geom_point(aes(col= loan), size=1)+
  ggtitle("PCA of Credict Assessment")
```

# Heat map for continuous variables
```{r }
my.cor<-cor(bank_20[,-c(2,3,4,5,6,7,8,9,10,15,21)])
my.cor
library(gplots)
library(ggplot2)
heatmap.2(my.cor,col=redgreen(75), 
          density.info="none", trace="none", dendrogram=c("row"), 
          symm=F,symkey=T,symbreaks=T, scale="none")
```


```{r }

```

```{r }

```


```{r }

```
